// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modbus} from '../models';
import {profiles} from '../models';

export function Connect(arg1:modbus.ConnectRequest):Promise<modbus.ConnectionStatus>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect():Promise<modbus.ConnectionStatus>;

export function GetConnectionStatus():Promise<modbus.ConnectionStatus>;

export function GetFrameLogs():Promise<Array<modbus.FrameLog>>;

export function ListProfiles():Promise<Array<profiles.Profile>>;

export function PreviewWriteMultipleCoils(arg1:modbus.WriteMultipleCoilsRequest):Promise<modbus.WritePreview>;

export function PreviewWriteMultipleRegisters(arg1:modbus.WriteMultipleRegistersRequest):Promise<modbus.WritePreview>;

export function PreviewWriteSingleCoil(arg1:modbus.WriteSingleCoilRequest):Promise<modbus.WritePreview>;

export function PreviewWriteSingleRegister(arg1:modbus.WriteSingleRegisterRequest):Promise<modbus.WritePreview>;

export function ReadBits(arg1:modbus.ReadBitsRequest):Promise<modbus.ReadBitsResponse>;

export function ReadRegisters(arg1:modbus.ReadRegistersRequest):Promise<modbus.ReadRegistersResponse>;

export function SaveProfile(arg1:profiles.Profile):Promise<void>;

export function WriteMultipleCoils(arg1:modbus.WriteMultipleCoilsRequest):Promise<void>;

export function WriteMultipleRegisters(arg1:modbus.WriteMultipleRegistersRequest):Promise<void>;

export function WriteSingleCoil(arg1:modbus.WriteSingleCoilRequest):Promise<void>;

export function WriteSingleRegister(arg1:modbus.WriteSingleRegisterRequest):Promise<void>;
