// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetFrameLogs() {
  return window['go']['main']['App']['GetFrameLogs']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function PreviewWriteMultipleCoils(arg1) {
  return window['go']['main']['App']['PreviewWriteMultipleCoils'](arg1);
}

export function PreviewWriteMultipleRegisters(arg1) {
  return window['go']['main']['App']['PreviewWriteMultipleRegisters'](arg1);
}

export function PreviewWriteSingleCoil(arg1) {
  return window['go']['main']['App']['PreviewWriteSingleCoil'](arg1);
}

export function PreviewWriteSingleRegister(arg1) {
  return window['go']['main']['App']['PreviewWriteSingleRegister'](arg1);
}

export function ReadBits(arg1) {
  return window['go']['main']['App']['ReadBits'](arg1);
}

export function ReadRegisters(arg1) {
  return window['go']['main']['App']['ReadRegisters'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function WriteMultipleCoils(arg1) {
  return window['go']['main']['App']['WriteMultipleCoils'](arg1);
}

export function WriteMultipleRegisters(arg1) {
  return window['go']['main']['App']['WriteMultipleRegisters'](arg1);
}

export function WriteSingleCoil(arg1) {
  return window['go']['main']['App']['WriteSingleCoil'](arg1);
}

export function WriteSingleRegister(arg1) {
  return window['go']['main']['App']['WriteSingleRegister'](arg1);
}
